name: Build Web app and APK files

on:
  push:
    tags:
      - 'dev*.*.*'

env:
  APK_PATH: build/app/outputs/flutter-apk/app-release.apk

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '17.x' 

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '3.22.3' # becareful about your current flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Enable Web
      run: flutter config --enable-web

    - name: Build Web
      run: flutter build web --web-renderer canvaskit # enable convaskit for mobile browsers
  
    - run: ls build/web
    
    - uses: lowply/deploy-firebase@v0.0.5
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_NAME }}

    - name: Build APK
      run: flutter build apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: ${{ env.APK_PATH }}
    
    - name: Send Message to Telegram on Success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        document: ${{ env.APK_PATH }}
        message: |
          ✔ Successful deployment on develop (Flutter):

          There is a new release: ${{ secrets.PROJECT_WEB_URL }}

          ${{ github.event.head_commit.message }}
    
          by ${{ github.event.head_commit.committer.name }} (${{ github.event.head_commit.committer.username }})
          
          ${{ github.event.head_commit.url }}


    - name: Send Message to Telegram on Failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ❌ Failed deployment on develop (Flutter):
    
          ${{ github.event.head_commit.message }}
    
          by ${{ github.event.head_commit.committer.name }} (${{ github.event.head_commit.committer.username }})

          ${{ github.event.head_commit.url }}
